name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    steps:
      - name: Prepare
        run: ''

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew assembleDebug

      - name: Test
        run: ./gradlew testDebugUnitTest

      - name: Lint
        run: ./gradlew lintDebug ktlintCheck

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        if: github.ref != 'refs/heads/master'
        with:
          ruby-version: '2.6'
          architecture: 'x64'

      - name: Run Danger
        if: github.ref != 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler
          bundle install
          danger
